# Generated by Django 5.2.9 on 2025-12-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.TextField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Informação',
                'verbose_name_plural': 'Informações',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('posicao', models.CharField(choices=[('goleiro', 'Goleiro'), ('lateral_direito', 'Lateral Direito'), ('lateral_esquerdo', 'Lateral Esquerdo'), ('zagueiro', 'Zagueiro'), ('volante', 'Volante'), ('meio_campista', 'Meio-campista'), ('extremo', 'Extremo/Direita'), ('atacante', 'Atacante')], max_length=20, verbose_name='Posição')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('foto', models.URLField(verbose_name='URL da Foto')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['nome'],
            },
        ),
    ]
